-- Orquestación del reentrenamiento + materialización, agendable con un TASK.
CREATE OR REPLACE PROCEDURE ANALYTICS.ML.SP_APPLY_SEGMENTS(N_CLUSTERS INTEGER DEFAULT 5)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    CALL ANALYTICS.ML.SP_TRAIN_KMEANS_SEGMENTS('ANALYTICS.MARTS.INT_CUSTOMER_FEATURES', :N_CLUSTERS);
    RETURN 'Segmentos ML actualizados.';
END;
$$;

-- Tarea agendada (usa el warehouse ML). Se reanuda con ALTER TASK ... RESUME.
CREATE OR REPLACE TASK ANALYTICS.ML.TASK_RETRAIN_SEGMENTS
    WAREHOUSE = ML_WH
    SCHEDULE = 'USING CRON 0 7 * * * America/Bogota'
AS
    CALL ANALYTICS.ML.SP_APPLY_SEGMENTS(5);
