-- RBAC con privilegio mínimo. Tres roles funcionales.
CREATE ROLE IF NOT EXISTS LOADER;       -- ingesta a RAW
CREATE ROLE IF NOT EXISTS TRANSFORMER;  -- dbt + ML
CREATE ROLE IF NOT EXISTS BI_READER;    -- solo lectura de marts

-- LOADER
GRANT USAGE ON WAREHOUSE LOAD_WH TO ROLE LOADER;
GRANT USAGE ON DATABASE ANALYTICS TO ROLE LOADER;
GRANT USAGE ON SCHEMA ANALYTICS.RAW TO ROLE LOADER;
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS.RAW TO ROLE LOADER;

-- TRANSFORMER
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE TRANSFORMER;
GRANT USAGE ON WAREHOUSE ML_WH TO ROLE TRANSFORMER;
GRANT ALL ON DATABASE ANALYTICS TO ROLE TRANSFORMER;
GRANT ALL ON ALL SCHEMAS IN DATABASE ANALYTICS TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE ANALYTICS TO ROLE TRANSFORMER;

-- BI_READER (consumo desde Tableau/Power BI/Looker)
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE BI_READER;
GRANT USAGE ON DATABASE ANALYTICS TO ROLE BI_READER;
GRANT USAGE ON SCHEMA ANALYTICS.MARTS TO ROLE BI_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA ANALYTICS.MARTS TO ROLE BI_READER;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA ANALYTICS.MARTS TO ROLE BI_READER;
